on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: batencoder.azurecr.io
        username: ${{ secrets.acr_batencoder_username }}
        password: ${{ secrets.acr_batencoder_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t batencoder.azurecr.io/kmac:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push batencoder.azurecr.io/kmac:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_kmac_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep darkencoder | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace darkencoder`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: darkencoder
        container-registry-url: batencoder.azurecr.io
        container-registry-username: ${{ secrets.acr_batencoder_username }}
        container-registry-password: ${{ secrets.acr_batencoder_password }}
        secret-name: kmacdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: darkencoder
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          batencoder.azurecr.io/kmac:${{ github.sha }}
        imagepullsecrets: |
          kmacdockerauth
